### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by mbutler808** [quinnmoon11/QUINN-Rclass-project#1]
https://github.com/quinnmoon11/QUINN-Rclass-project/blob/6071cbb89d24ff10e13bab422d86c99c11f0fb04/Code/Processing_code/QuinnProcessing.R#L53-L58

Remember that part of the assignment is to write code that is worthy of being a finished product (for publication or for pay). So you will want to edit out the instructions and replace it with concise, informative comments that will be suitable for the R literate public. 

Also, do you really want to print out the entire raw dataset? If you have a purose for doing that, you may want to put it at the end and explain.

**Comment by quinnmoon11** [comment]
Corrected
