### ISSUE TITLE
repetition

### ISSUE THREAD

**Issue by mbutler808** [quinnmoon11/QUINN-Rclass-project#2]
https://github.com/quinnmoon11/QUINN-Rclass-project/blob/6071cbb89d24ff10e13bab422d86c99c11f0fb04/Code/Processing_code/QuinnProcessing.R#L82-L101

I know I said to check after each edit but this causes a lot of repetition. For this I think itʻs OK to just have one check at the end of these typo fixes.

**Comment by quinnmoon11** [comment]
Corrected
