### ISSUE TITLE
keep dictionary with data

### ISSUE THREAD

**Issue by mbutler808** [quinnmoon11/QUINN-Rclass-project#4]
https://github.com/quinnmoon11/QUINN-Rclass-project/blob/6071cbb89d24ff10e13bab422d86c99c11f0fb04/Code/Processing_code/QuinnProcessing.R#L278-L280

This should be saved to the processed data folder.   This dictionary is for the cleaned data, so keep it together

**Comment by quinnmoon11** [comment]
Corrected
